### ISSUE TITLE
Fusion no longer exports .tsv tool files

### ISSUE THREAD

**Issue by gerritv** [TimPaterson/CNC-Tool-Library-Manager#2]
Thank you for an excellent article in DM and wonderful tool, it solves my sync problems nicely. I'm a huge fan of VBA in the Office suite, a highly under-appreciated tool.

Recently Fusion started using .csv instead of .tsv for its exports, and in the process changed the heading from row 3 to 1 and also the heading labels.

To get the new file imported, I changed:
Rules: tab separated for Fusion to FALSE
Rules: Header row to 1

In sub SortLibrary:
I altered the Find line to use xlPart instead of xlWhole. This is because the Header names now include the internal paramet name, e.g. 'Number(tool_number)' where in the tsv it was just 'number'.

In sub BuildMap:
change Find xlWhole to xlPart

**Comment by TimPaterson** [comment]
Thanks for alerting me to the change in Fusion and sharing your fix. Unfortunately, the problem is way worse, at least for me. I have quotes (for inches) in my descriptions, and Fusion escapes them with '\' while Excel wants them doubled as "". This totally screws up the Excel import as CSV. Also, measurments like tool diameter are now always in millimeters, it seems. Maybe you're metric already and aren't affected by either of these issues, but my tool library is in inches.

The new tool library is a "preview" feature that can be turned off, and that's what I'm going to do for now. As a preview, maybe Autodesk will be open to some changes that will make the transition easier.

I haven't seen that the magazine article was out yet...

**Comment by gerritv** [comment]
The article is in DM Summer 2022.
I would like to work on this, can you provide a short example file? Is the quote like 0.25" ? I'm not seeing the metric dims in the inch file.
My present imperial Fusion tool lib is a bit messed up due to export//import from/to Inventor and Fusion so probably not a good example to start off with.

I have both metric and imperial tools so this will affect me as well.

**Comment by TimPaterson** [comment]
It turns out I was using an old version of Fusion 360. The two issues I mention of quotes and units have both been fixed. All that needs to be changed are the rules. 

It is important NOT to change Find to xlPart. Instead, the rules should just include all the text of the name. There are, for example, several columns with "Description" in the name. I will try to commit these changes soon.

**Comment by gerritv** [comment]
Ah, ok, I didn't look at all 116 columns of the Fusion file :-)

I will test once available. Thank you.

**Comment by gerritv** [comment]
Tested and working, tku.
